# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

---

In [3]:
import numpy as np
num = np.arange(1,10+1)
print(num)

[ 1  2  3  4  5  6  7  8  9 10]


### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

---

In [23]:
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

---

In [57]:
evennum = np.linspace(0,5,10)
print(evennum)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

---

In [73]:
identity = np.eye(5,5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

---

In [211]:
np.random.rand(4,4)

array([[0.76684861, 0.14063166, 0.43092892, 0.76208787],
       [0.9159852 , 0.16878286, 0.02195326, 0.54788234],
       [0.78265939, 0.07138067, 0.15128588, 0.66768276],
       [0.57509578, 0.88536152, 0.479963  , 0.76400065]])

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

---

In [213]:
random.shape

(4, 4)

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

---

In [225]:
rando = np.random.randint(1,5,16)
print(rando.reshape(4,4))

[[3 3 3 4]
 [2 2 2 1]
 [1 4 4 4]
 [1 4 1 2]]


### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

---

In [229]:
rando.dtype
random.dtype

dtype('float64')

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

---

In [279]:
int = np.arange(1,100+1)
for i in int:
    if i%2==0:
        print(i)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

---

In [325]:
randmatrix = np.random.randint(10,50, size=(6,6))
print(randmatrix)

[[29 32 44 43 49 17]
 [32 35 26 25 19 11]
 [15 48 26 40 49 25]
 [10 13 47 24 46 34]
 [49 35 39 30 33 24]
 [37 23 13 22 10 11]]


In [373]:
a = np.min(randmatrix)
b = np.max(randmatrix)
c = np.min(randmatrix, axis = 0)
d = np.min(randmatrix, axis = 1)
print(a)
print(b)
print(c)
print(d)

10
49
[10 13 13 22 10 11]
[17 11 15 10 24 10]


### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

---

In [401]:
slic = np.random.randint(0,10, size = (2,9))
slic

array([[6, 8, 8, 0, 0, 5, 5, 7, 9],
       [6, 2, 9, 7, 4, 0, 4, 2, 8]])

In [403]:
sli = slic.reshape(3,6)
sli

array([[6, 8, 8, 0, 0, 5],
       [5, 7, 9, 6, 2, 9],
       [7, 4, 0, 4, 2, 8]])

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

---

In [413]:
ar = np.random.randint(0,100, size = (5,5))
sum = np.sum(ar)
print(ar, "and the sum of all element is:",sum)

[[12 13 32 33 16]
 [57 46 64 47 71]
 [26 36 92 96 84]
 [69 90 36 84 10]
 [95 54 85 17 26]] and the sum of all element is: 1291


### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

---

In [427]:
print("The Mean of the array is:",np.mean(ar))
print("The Mediam of the array is:", np.median(ar))
print("The standard deviation of the array is:", np.std(ar))

The Mean of the array is: 51.64
The Mediam of the array is: 47.0
The standard deviation of the array is: 28.898276765232904


### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

---

In [429]:
print("The maximum value of the array is:",np.max(ar))
print("The maximum value of the array is:",np.min(ar))

The maximum value of the array is: 96
The maximum value of the array is: 10


### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

---

In [519]:
rnd = np.random.randint(200,500, 20)
print(rnd, "And the maximum is:",np.argmax(rnd))

[200 490 388 370 341 226 231 363 283 222 258 470 230 405 435 233 326 381
 238 214] And the maximum is: 1


### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

---

In [553]:
element = np.random.randint(0,10,20)
reverse = np.flip(element)
print(element, "and their reserve is:",reverse)

[9 0 5 6 5 6 3 3 4 4 3 0 0 4 5 0 1 6 8 8] and their reserve is: [8 8 6 1 0 5 4 0 0 3 4 4 3 3 6 5 6 5 0 9]


### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

---

In [579]:
A = np.random.randint(0,9, size = (3,3))
B = np.random.randint(1,6, size = (3,3))
multiplymatrix = A * B
print(A)
print("\n")
print(B)
print("\n")
print("The multiplication of the two matrices are:" "\n", multiplymatrix)

[[2 0 5]
 [8 0 4]
 [0 1 5]]


[[1 2 2]
 [1 3 3]
 [4 5 2]]


The multiplication of the two matrices are:
 [[ 2  0 10]
 [ 8  0 12]
 [ 0  5 10]]


### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

---

In [67]:
import numpy as np
dia = np.array([3,4,5,15])
print("The diagonal element are:" "\n", np.diag(dia))
arr=np.diag(dia)
arr1=np.diag(arr)
arr1

The diagonal element are:
 [[ 3  0  0  0]
 [ 0  4  0  0]
 [ 0  0  5  0]
 [ 0  0  0 15]]


array([ 3,  4,  5, 15])

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

---

In [95]:
AB = np.random.randint(1,5, size = (2,2))
CD = np.random.randint(3,5, size = (2,2))
print(AB)
print("\n")
print(CD)
print("\n")
result = np.dot (AB, CD)
print(result)

[[4 1]
 [4 2]]


[[3 3]
 [4 3]]


[[16 15]
 [20 18]]


### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

---

In [99]:
AB.flatten()

array([4, 1, 4, 2])

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

---

In [103]:
np.vstack((AB,CD))

array([[4, 1],
       [4, 2],
       [3, 3],
       [4, 3]])

### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

---

In [105]:
np.hstack((AB,CD))

array([[4, 1, 3, 3],
       [4, 2, 4, 3]])

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

---

In [117]:
spli = np.random.randint(0,5,9)
np.split(spli, 3)

[array([1, 3, 3]), array([0, 1, 0]), array([0, 1, 4])]

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

---

In [127]:
rou1 = np.random.rand(4,4)
rou2= np.round(rou1,2)
print(rou2)

[[0.38 0.85 0.77 0.82]
 [0.97 0.79 0.66 0.71]
 [0.4  0.21 0.95 0.48]
 [0.66 0.18 0.8  0.22]]


### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

---

In [133]:
un = np.unique(spli)
print(spli)
print(un)

[1 3 3 0 1 0 0 1 4]
[0 1 3 4]


### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

---

In [175]:
bb = np.array([1,2,3,4,5,6])
bb[bb < 3] = 10
print(bb)

[10 10  3  4  5  6]


### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

---

In [177]:
np.cumsum(bb)

array([10, 20, 23, 27, 32, 38])

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

---

In [185]:
created = np.random.randint(0,10, size = (10,10))
print(created)
np.count_nonzero(created)

[[4 1 2 8 7 7 0 5 7 1]
 [6 7 4 6 0 5 4 8 2 6]
 [5 8 3 0 7 3 5 7 8 4]
 [7 1 8 9 7 5 0 1 8 1]
 [9 7 9 6 0 6 2 3 3 0]
 [3 2 2 1 3 9 4 4 4 1]
 [6 2 3 4 0 8 6 4 1 8]
 [7 0 6 4 6 2 8 5 7 5]
 [8 0 9 1 3 7 5 7 4 7]
 [2 8 2 0 8 7 1 8 1 1]]


90

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

---

In [187]:
np.sort(bb)

array([ 3,  4,  5,  6, 10, 10])

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

---

In [197]:
created = np.random.randint(0,10, size = (3,3))
print("\n")
print(created)
print("\n")
np.sum(created, axis = 0)



[[3 1 5]
 [9 7 6]
 [9 7 4]]




array([21, 15, 15])

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

---

In [203]:
array2 = np.random.rand(3, 3)
min_val = np.min(array2)
max_val = np.max(array2)

normalized_array = (array2 - min_val) / (max_val - min_val)

print("Original array:")
print(array2)
print("\nNormalized array:")
print(normalized_array)


Original array:
[[0.39075222 0.57275051 0.26203498]
 [0.01153632 0.80205378 0.73821084]
 [0.75034012 0.71450358 0.73103251]]

Normalized array:
[[0.47970591 0.70993269 0.31687935]
 [0.         1.         0.91923906]
 [0.93458253 0.88924951 0.9101585 ]]


### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

---

In [211]:
a1 = np.random.randint(5,9, size = (3,3))
a2 = np.random.randint(20,25, size = (3,3))
a1 @ a2

array([[488, 536, 552],
       [467, 515, 529],
       [468, 512, 530]])

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

---

In [215]:
np.trace(a1)

65

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

---

In [245]:
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Swap the first row (index 0) with the second row (index 1)
array_2d[[0, 1]] = array_2d[[1, 0]]

print("\n Array after swapping rows 0 and 1:")
print(array_2d)



 Array after swapping rows 0 and 1:
[[4 5 6]
 [1 2 3]
 [7 8 9]]


### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

---

In [225]:
bb.reshape(-1,1)

array([[10],
       [10],
       [ 3],
       [ 4],
       [ 5],
       [ 6]])

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

---

In [237]:
matrix = np.random.randint(1,9, size = (5,5))
print("\n")
print(matrix)
determinant = np.linalg.det(matrix)
print(determinant)



[[4 6 6 6 2]
 [6 5 6 2 1]
 [3 1 8 5 7]
 [7 7 1 4 5]
 [4 6 1 6 6]]
-827.9999999999992


### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

---

In [247]:
matrix = np.array([[4, 2],[1, 3]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(matrix)
print("\n")
print(eigenvalues)
print("\n")
print(eigenvectors)

[[4 2]
 [1 3]]


[5. 2.]


[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

In [253]:
A = np.array([[2, 3],
              [4, 1]])
b = np.array([5, 11])
solution = np.linalg.solve(A, b)
print("my answer is:", solution)

my answer is: [ 2.8 -0.2]


### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

In [257]:
original_array = np.array([10, 20, 30, 40, 50])
mean = 0
std_dev = 5
noise = np.random.normal(mean, std_dev, original_array.shape)
noisy_array = original_array + noise
print(original_array)
print(noise)
print(noisy_array)

[10 20 30 40 50]
[1.30114899 1.41400009 2.99513156 1.47535019 5.16966356]
[11.30114899 21.41400009 32.99513156 41.47535019 55.16966356]


### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

In [265]:
ele = np.random.randint(1,10, size = (4,4))
print(ele)
np.diag(ele)

[[4 1 3 4]
 [6 6 8 8]
 [3 8 1 8]
 [5 7 7 5]]


array([4, 6, 1, 5])

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---